Repository canonical/canonicalwebteam.blog, pull requests merged in 2019-08, with the labels that each got.

#105 Adds Atom feed View to both Django and Flask
  canonicalwebteam/blog/common_view_logic.py
  canonicalwebteam/blog/django/views.py
  canonicalwebteam/blog/flask/views.py
  canonicalwebteam/blog/wordpress_api.py
  fixtures/vcr_cassettes/django_homepage.yaml
  fixtures/vcr_cassettes/get_article_context.yaml
  fixtures/vcr_cassettes/get_complete_article.yaml
  fixtures/vcr_cassettes/get_group_context.yaml
  fixtures/vcr_cassettes/get_index_context.yaml
  fixtures/vcr_cassettes/get_topic_context.yaml
  tests/test_wordpress_api.py
Labels: Review: Code +1, Review: QA +1

#107 Fix up setting default title for django version of blog module
  CHANGELOG.txt
  canonicalwebteam/blog/django/views.py
  canonicalwebteam/blog/wordpress_api.py
  pyproject.toml
Labels: Review: Code +1

#110 Use uncached sessions for feed API calls
  CHANGELOG.txt
  canonicalwebteam/blog/common_view_logic.py
  canonicalwebteam/blog/wordpress_api.py
  pyproject.toml
Labels: Review: Code +1

#116 Add auto-generated setup.py
  .gitignore
  README.md
  poetry.lock
  pyproject.toml
  requirements.txt
  setup.py
Labels: Review: Code needed, Review: QA needed

#114 Add feeds endpoints for authors, groups and topics
  CHANGELOG.txt
  canonicalwebteam/blog/common_view_logic.py
  canonicalwebteam/blog/django/urls.py
  canonicalwebteam/blog/django/views.py
  canonicalwebteam/blog/feeds.py
  canonicalwebteam/blog/flask/views.py
  canonicalwebteam/blog/wordpress_api.py
  constraints.txt
  poetry.lock
  pyproject.toml
  requirements.txt
  setup.py
Labels: Review: Code +1, Review: QA +1

#117 Order feeds from most recent to oldest
  CHANGELOG.txt
  canonicalwebteam/blog/feeds.py
  pyproject.toml
  setup.py
Labels: Review: Code +1, Review: QA +1

#113 Update 'Getting started' docs in README
  README.md
Labels: Review: Code +1

#118 v3.0.0: Change Flask interface to expose BlogViews
  .gitignore
  CHANGELOG.txt
  README.md
  canonicalwebteam/blog/__init__.py
  canonicalwebteam/blog/app.py
  canonicalwebteam/blog/common_view_logic.py
  canonicalwebteam/blog/django/views.py
  canonicalwebteam/blog/flask.py
  canonicalwebteam/blog/flask/__init__.py
  pyproject.toml
  setup.py
  tests/test_common_view_logic.py
  tests/test_django_views.py
Labels: Review: Code +1, Review: QA +1
