Repository canonical/canonicalwebteam.blog, pull requests merged in 2019-03, with the labels that each got.

#10 Creates and exports django app on blog module
  canonicalwebteam/blog/app.py
  canonicalwebteam/blog/django/__init__.py
  canonicalwebteam/blog/django/apps.py
  canonicalwebteam/blog/django/urls.py
  canonicalwebteam/blog/django/views.py
  canonicalwebteam/blog/flask/views.py
Labels: Review: Code +1, Review: QA +1

#11 Implement django view logic
  .gitignore
  README.md
  canonicalwebteam/blog/__init__.py
  canonicalwebteam/blog/common_view_logic.py
  canonicalwebteam/blog/django/apps.py
  canonicalwebteam/blog/django/urls.py
  canonicalwebteam/blog/django/views.py
  canonicalwebteam/blog/flask/views.py
  setup.py
  tests/__init__.py
  tests/test_common_view_logic.py
Labels: Review: Code +1, Review: QA +1

#14 Updates version to 1.0
  setup.py
Labels: Review: Code needed

#17 Fixes imports, group caching and settings access
  canonicalwebteam/blog/common_view_logic.py
  canonicalwebteam/blog/django/urls.py
  canonicalwebteam/blog/django/views.py
  canonicalwebteam/blog/wordpress_api.py
  setup.py
Labels: Review: Code needed

#18 Add CIrcleCI tests
  .circleci/config.yml
  setup.py
  tests/test_common_view_logic.py
Labels: Review: Code +1, Review: QA +1

#13 Allow excluding tags
  canonicalwebteam/blog/wordpress_api.py
  setup.py
  tests/test_wordpress_api.py
Labels: Review: Code +1
