Repository canonical/canonicalwebteam.blog, pull requests merged in 2019-09, with the labels that each got.

#119 Fix link in README
  README.md
Labels: Review: Code +1

#120 Fix 404s for groups
  .gitignore
  CHANGELOG.txt
  canonicalwebteam/blog/common_view_logic.py
  canonicalwebteam/blog/django/views.py
  canonicalwebteam/blog/flask.py
  pyproject.toml
  setup.py
Labels: Review: Code +1

#121 v3.1.0: Allow setting feed_description through build_blueprint
  CHANGELOG.txt
  README.md
  canonicalwebteam/blog/common_view_logic.py
  canonicalwebteam/blog/feeds.py
  poetry.lock
  pyproject.toml
  setup.py
Labels: Review: Code +1, Review: QA +1

#122 Fixes for /latest-news JSON endpoint
  CHANGELOG.txt
  canonicalwebteam/blog/common_view_logic.py
  canonicalwebteam/blog/flask.py
  pyproject.toml
  setup.py
Labels: Review: Code +1, Review: QA +1

#123 v3.1.1: Filter /latest-news JSON endpoint by group
  CHANGELOG.txt
  canonicalwebteam/blog/common_view_logic.py
  canonicalwebteam/blog/flask.py
  pyproject.toml
  setup.py
Labels: Review: Code needed, Review: QA needed

#124 Remove outdated blog instruction
  README.md
Labels: Review: Code +1
